import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <Link href="/" passHref>
            Home
          </Link>
          <Link href="/events" passHref>
            Events
          </Link>
          <Link href="/about-us" passHref>
            About us
          </Link>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((event, index) => (
          <div key={index}>
            <Link href={`/events/${event.id}`} passHref>
              <Image
                width={300}
                height={300}
                src={event.image}
                alt={event.id}
              />
              <h2>{event.title}</h2>
              <p>{event.description}</p>
            </Link>
          </div>
        ))}
      </main>
      <footer>
        <p>copyright </p>
      </footer>
    </>
  );
}
export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");

  return {
    props: {
      data: events_categories,
    },
  };
}
